name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feature:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: idVersionStep
             
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        VERSION: ${{ steps.idVersionStep.outputs.version }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando login"
        echo "New version: $VERSION"

    - name: Build Docker Image
      env:
         VERSION: ${{ steps.idVersionStep.outputs.version }}
      run: |
        docker build . -t jos3docker/docker-graphql:$VERSION
        docker build . -t jos3docker/docker-graphql:latest

    - name: Push Docker Image
      env:
         VERSION: ${{ steps.idVersionStep.outputs.version }}
      run: |
        docker push jos3docker/docker-graphql:$VERSION
        docker push jos3docker/docker-graphql:latest

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
